### PR TITLE
feat: make initial path optional

### PR DESCRIPTION
**Pull request by sbekrin**
Hey there 👋

What do you think about proposed changes? Using current working directory as a default initial path aligns with what yarn [does](https://github.com/yarnpkg/yarn/blob/ddf2f9ade211195372236c2f39a75b00fa18d4de/src/config.js#L223).

### CODE REVIEW

**Comment by eventualbuddha** [comment]
Hi @sergeybekrin, thanks for the suggestion. I think this would be fairly reasonable, but we should include tests for it. Can you add a test or two to cover calling without an argument? Thanks!

**Comment by sbekrin** [comment]
@eventualbuddha yep sure, will do somewhere this week. Do you have plans on dropping Node 4 support by any chance?

**Comment by eventualbuddha** [comment]
Once the current dependencies for this library drop node 4, then we will too.

**Comment by sbekrin** [comment]
@eventualbuddha I've updated PR with a new test. I've created dummy module `cwd-find-root.js` to be able execute it against different cwd, not sure if there's better way.

**Comment by eventualbuddha** [comment]
This seems fine to me. @lennyburdette and @thetimothyp, what do you think?

**Review by lennyburdette — APPROVED** [review]
LGTM!

**Comment by sbekrin** [comment]
@eventualbuddha @lennyburdette hey folks, any update on this one?

**Comment by eventualbuddha** [comment]
Sorry, tragedy of the commons. Merging!

**Comment by eventualbuddha** [comment]
Published in v1.2.0.

**Pull request merged**
